services:
  - type: web
    name: interest-rate-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python advanced_dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: true